version: "3.8"
services:
  app:
    container_name: skill-sharing-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevents host node_modules from overwriting container node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/skillsharing
      - JWT_SECRET=dedff887502d5660867d7782c14e8b8fff2c0fc99df04ad46e0ca8960d8c8b251960f9ee1fd1d595e854ddc007dab2505794432c1a44d279816601184af6176a

  db:
    container_name: skill-sharing-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skillsharing
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: